### ISSUE TITLE
Error while running the application

### ISSUE THREAD

**Issue by lfoppiano** [Marame/M2Internship_Entity_Resolution#12]
When testing the `documents.csv` and `queries.csv` I get the following error: 

```
$$$$$$$$$$$$ Results for Vector Space Model $$$$$$$$$$$$$
Exception in thread "main" java.util.UnknownFormatConversionException: Conversion = '
'
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2565)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at Main.startTesting(Main.java:43)
	at Main.main(Main.java:22)
```

**Comment by Marame** [comment]
fix#12 : fixing format : putting "%-10s%-20s%-20s%-20s" for the , instead of "%-10s%-20s%-20s%-20s%"
