### ISSUE TITLE
Hardcoded paths in the Main.java

### ISSUE THREAD

**Issue by lfoppiano** [Marame/M2Internship_Entity_Resolution#2]
Seems that there are some hardcoded paths in the Main.java class: 

When I run it on my machine these results in the following message: 
```
$$$$$$$$$$$$ Results for Vector Space Model $$$$$$$$$$$$$
java.io.FileNotFoundException: /home/romdhane/Documents/stage_inria/queries (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at Main.startTesting(Main.java:42)
	at Main.main(Main.java:27)
version   Stemming  Lemmatizing

===================================================
Binary    NaN||     NaN
      TF        NaN||     NaN
      TF/IDF    NaN||     NaN
      BM25      NaN||     NaN
      
$$$$$$$$$$$$ Results for Language Model $$$$$$$$$$$$$
version   Stemming  Lemmatizing

===================================================
jelinek-mercer      NaN||     NaN
      dirichlet-prior     NaN||     NaN
      
```

**Comment by Marame** [comment]
resolved : the paths are now introduced as arguments by the user

**Comment by lfoppiano** [comment]
commit number?
